config:
  default: true
  MD013: false # line length (handled case-by-case)
  MD033: false # allow HTML for README signature

globs:
  - README.md
  - docs/README.md
  - docs/agents/*.md
  - brand/README.md
