flowchart TD
  subgraph Channels["Event channels / queues"]
    narrativeTelemetry_70dfa1c5{{"narrativeTelemetry"}}
    useFirefly_test_2c284fc9{{"useFirefly.test"}}
    settings_cde0fb0d["settings"]
    useFirefly_4b28bfda["useFirefly"]
  end
  useFirefly_test_2c284fc9 -->|emit| settings_cde0fb0d
  useFirefly_4b28bfda -->|consume| settings_cde0fb0d
  classDef eventNode fill:#db2777,color:#fff