name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the details below.

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug in clear, simple terms
      placeholder: When I open a repository, the app crashes with...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: How can we reproduce the issue?
      placeholder: |
        1. Open the app
        2. Click "Open repo..."
        3. Select any git repository
        4. App crashes
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
      description: What should have happened?
      placeholder: The repository should open and show the commit timeline

  - type: input
    id: version
    attributes:
      label: App Version
      description: What version of Narrative are you running?
      placeholder: e.g., 0.3.1

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux
        - Windows

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs or error messages
      description: If you have error messages or logs, paste them here
      render: shell
